# Generated by Django 5.1.4 on 2025-01-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
