# Generated by Django 5.1.4 on 2025-01-11 20:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0002_alter_parkinglot_lat_alter_parkinglot_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='coords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=4),
        ),
    ]
