# Generated by Django 5.1.4 on 2025-01-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0003_alter_parking_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='coords',
            field=models.JSONField(verbose_name=models.IntegerField()),
        ),
    ]
