# Generated by Django 5.1.4 on 2025-01-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0004_alter_parking_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='license_number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
