# Generated by Django 5.1.4 on 2025-01-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0006_user_username_alter_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
