# Generated by Django 5.1.4 on 2025-01-20 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='parkingAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('password', models.TextField()),
                ('license_number', models.CharField(max_length=8)),
                ('car_type', models.CharField(max_length=50, null=True)),
                ('car_year', models.PositiveIntegerField(null=True)),
                ('car_color', models.CharField(max_length=50, null=True)),
                ('car_model', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
