# Generated by Django 5.1.4 on 2025-01-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0009_delete_parkingauth_parking_driver_parking_is_saved_and_more'),
        ('parkingAuth', '0002_parkingauth_is_active_parkingauth_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking', to='parkingAuth.parkingauth'),
        ),
    ]
