# Generated by Django 5.1.4 on 2025-01-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0010_alter_parking_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='license_number',
        ),
    ]
