# Generated by Django 5.1.4 on 2025-01-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0011_remove_parking_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='coords',
            field=models.JSONField(),
        ),
    ]
