# Generated by Django 5.1.4 on 2025-03-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0012_alter_parking_coords'),
        ('parkingAuth', '0003_alter_parkingauth_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='parking_lots_own',
            field=models.ManyToManyField(blank=True, null=True, related_name='parkingLots', to='parkingAuth.parkingauth'),
        ),
    ]
