# Generated by Django 5.1.4 on 2025-03-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0013_parkinglot_parking_lots_own'),
        ('parkingAuth', '0003_alter_parkingauth_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='parking_lots_own',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='owner',
            field=models.ManyToManyField(blank=True, null=True, related_name='lots', to='parkingAuth.parkingauth'),
        ),
    ]
