# Generated by Django 5.1.4 on 2025-03-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0014_remove_parkinglot_parking_lots_own_parkinglot_owner'),
        ('parkingAuth', '0003_alter_parkingauth_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='lots', to='parkingAuth.parkingauth'),
        ),
    ]
