# Generated by Django 5.1.4 on 2025-03-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0015_alter_parkinglot_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='address',
            field=models.TextField(default='Address not found', max_length=200),
        ),
    ]
