# Generated by Django 5.1.4 on 2025-03-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0016_parkinglot_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='unauthorized_parking',
            field=models.BooleanField(default=False),
        ),
    ]
