# Generated by Django 5.1.4 on 2025-03-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0017_parking_unauthorized_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='unauthorized_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
