# Generated by Django 5.1.4 on 2025-01-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingauth',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingauth',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
