# Generated by Django 5.1.4 on 2025-03-05 12:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0015_alter_parkinglot_owner'),
        ('parkingAuth', '0003_alter_parkingauth_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='parkingAuth.parkingauth')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='parkingApp.parkinglot')),
            ],
        ),
    ]
