# Generated by Django 5.1.4 on 2025-03-08 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingAuth', '0004_parkinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='parkinghistory',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
