# Generated by Django 5.1.4 on 2025-03-26 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0018_parking_unauthorized_notification_sent'),
        ('parkingAuth', '0005_alter_parkinghistory_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinghistory',
            name='parking_lot',
        ),
        migrations.AddField(
            model_name='parkinghistory',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='parkingApp.parking'),
        ),
        migrations.AlterField(
            model_name='parkingauth',
            name='license_number',
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
